"""Increase collective_name length

Revision ID: 37e23d2199a0
Revises: 50ab80b0c759
Create Date: 2022-06-03 04:48:11.913711

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "37e23d2199a0"
down_revision = "50ab80b0c759"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "accession",
        "accession_number",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    op.alter_column(
        "author",
        "collective_name",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=3000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "author",
        "collective_name",
        existing_type=sa.String(length=3000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    op.alter_column(
        "accession",
        "accession_number",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
