"""Reduce more lengths

Revision ID: 405a03f1a932
Revises: 46f5b94b2d2e
Create Date: 2022-06-03 05:56:18.113566

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "405a03f1a932"
down_revision = "46f5b94b2d2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "abstract",
        "copyright_information",
        existing_type=sa.VARCHAR(length=2000),
        type_=sa.String(length=4000),
        existing_nullable=True,
    )
    op.alter_column(
        "citation",
        "medline_pgn",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=400),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "citation",
        "medline_pgn",
        existing_type=sa.String(length=400),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "abstract",
        "copyright_information",
        existing_type=sa.String(length=4000),
        type_=sa.VARCHAR(length=2000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
