"""Increase journal iso abbrev length

Revision ID: 50ab80b0c759
Revises: cb2fce4ff7c6
Create Date: 2022-06-03 01:50:05.176495

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "50ab80b0c759"
down_revision = "cb2fce4ff7c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "journal",
        "iso_abbreviation",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "journal",
        "iso_abbreviation",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
