"""Increase journal volume/issue length

Revision ID: cb2fce4ff7c6
Revises: d3a2d5b30f78
Create Date: 2022-06-02 23:46:45.738041

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cb2fce4ff7c6"
down_revision = "d3a2d5b30f78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "journal", "volume", existing_type=sa.VARCHAR(length=200), type_=sa.String(length=500), existing_nullable=True
    )
    op.alter_column(
        "journal", "issue", existing_type=sa.VARCHAR(length=200), type_=sa.String(length=500), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "journal", "issue", existing_type=sa.String(length=500), type_=sa.VARCHAR(length=200), existing_nullable=True
    )
    op.alter_column(
        "journal", "volume", existing_type=sa.String(length=500), type_=sa.VARCHAR(length=200), existing_nullable=True
    )
    # ### end Alembic commands ###
